export const ROOMS_RECEIVED = 'ROOMS_RECEIVED';
export const ROOM_CHOSEN = 'ROOM_CHOSEN';
export const ROOM_CREATED = 'ROOM_CREATED';
export const ROOM_DELETED = 'ROOM_DELETED';
export const OPEN_ROOM_MODAL = 'OPEN_ROOM_MODAL';
export const CLOSE_ROOM_MODAL = 'CLOSE_ROOM_MODAL';
export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';

export const MESSAGES_RECEIVED = 'MESSAGES_RECEIVED';
export const MESSAGES_CLEARED = 'MESSAGES_CLEARED';
export const MESSAGE_ADDED = 'MESSAGE_ADDED';

export const TOKEN_UPDATE = 'TOKEN_UPDATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_LIST_RECEIVED = 'USER_LIST_RECEIVED';

export const ERROR_DISPLAY = 'ERROR_DISPLAY';
export const ERROR_HIDE = 'ERROR_HIDE';
